version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "discord.js"
      - dependency-name: "mongoose"
      - dependency-name: "pokemon-api-wrapper"
      - dependency-name: "anilist-api-client"
